### ISSUE TITLE
Daniel: Introduction checklist

### ISSUE THREAD

**Issue by denrique-alvarez** [lab-antwerp-1/group-3#1]
- Setup: GitHub
  - [x] created this issue
  - [x] assigned myself
  - [x] moved the issue to the project board
- Setup: local
  - [x] pulled the most recent code from `main`/`master`
  - [x] created a new branch for my introduction
- Writing the content:
  - [x] added my intro file in `/people` according to group conventions
  - [x] linked to my file from `/README.md` according to group conventions
- Before pushing my branch:
  - [x] formatted the code
  - [ ] fixed all spelling mistakes and added new words to the dictionary
  - [x] fixed all linting mistakes
- After pushing my branch:
  - [x] created a new PR linked to this issue
  - [ ] make sure all of the checks passed
  - [x] assigned someone to review and merge my PR

**Comment by Darin-Hamouda** [comment]
Hi @denrique-alvarez 
I hope everything is good.
I just have some questions if you do not mind :)

**Comment by denrique-alvarez** [comment]
Hi @Darin-Hamouda , I just saw your message. Please send me a message through Slack so I can see it right away. Cheers!
