### ISSUE TITLE
Khaled: Introduction checklist

### ISSUE THREAD

**Issue by Khqled-syr** [lab-antwerp-1/group-3#11]
- [x] created this issue
  - [x] assigned myself
  - [x] moved the issue to the project board
- Setup: local
  - [x] pulled the most recent code from `main`/`master`
  - [x] created a new branch for my introduction
- Writing the content:
  - [ ] added my intro file in `/people` according to group conventions
  - [ ] linked to my file from `/README.md` according to group conventions
- Before pushing my branch:
  - [x] formatted the code
  - [x] fixed all spelling mistakes and added new words to the dictionary
  - [x] fixed all linting mistakes
- After pushing my branch:
  - [ ] created a new PR linked to this issue
  - [x] make sure all of the checks passed
  - [x] assigned someone to review and merge my PR
